name: BuildðŸ”¨, VerifyðŸ§ª on schedule

on:
  schedule:
    - cron: '0 3 * * Sat'
  workflow_dispatch:

jobs:
  install-pnpm-deps:
    uses: ./.github/workflows/_install-pnpm-deps.yaml
    with:
      use-pnpm-store-cache: false

  build-uniproc:
    needs: install-pnpm-deps
    uses: ./.github/workflows/_build-uniproc.yaml

  build-sveltecf:
    needs:
      - install-pnpm-deps
      - build-uniproc
    uses: ./.github/workflows/_build-sveltecf.yaml

  verify-uniproc:
    needs: build-uniproc
    uses: ./.github/workflows/_verify-uniproc.yaml

  verify-sveltecf:
    needs: build-sveltecf
    uses: ./.github/workflows/_verify-sveltecf.yaml
